name: QR
env:
  LABEL: QR202311
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: docker/login-action@v2
      - run: docker build -t app .
      - run: npm run test
