name: 8.x
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NPM Version'     
        required: true
jobs:
  publish-npm-module:
    runs-on: ubuntu-latest
    steps:
      - name: Verify valid version for develop
        if: ${{ github.ref_name }} == develop && ${{ !startsWith(github.event.inputs.version, '8') }}
        run: |
            echo "Error: NPM Version for the develop branch must be 8.x.x"
            exit 1
      - name: Verify valid version for uex
        if: ${{ github.ref_name }} == uex-main && ${{ !startsWith(github.event.inputs.version, '9') }}
        run: |
            echo "Error: NPM Version for the uex-main branch must be 9.x.x"
            exit 1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
