name: Unit Tests
on:
  pull_request:
    branches:
      - develop

jobs:
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run coverage